
#Laptop name
LOCAL_LAPTOP = "LAPTOP-XXXX"
FAKE_LAPTOP = "LAPTOP-XXXX"

#passwords for accessing local mysql systems
BACKEND_DB_PASS = "Rapok4bOFruQ"
BACKEND_LLM_PASS = "7HEstLQOwos1"


#openai_key under password
[7HEstLQOwos1]
OPENAI_API_KEY = "sk-..."

#mySQL DataLogger keys under password
[Rapok4bOFruQ]
MYSQL_HOST = "localhost"
MYSQL_USER = "user"
MYSQL_PASSWORD = "password"
MYSQL_DATABASE = "database_name"

[passwords]
# Follow the rule: username = "password"
presentation = "JlS1"

